result_dir: "/data/NCBR/projects/NCBR-strongyloides/"
rawdata_dir: "/data/NCBR/projects/NCBR-strongyloides/raw/"
genome_size: "42.6m"
coverage: "200"
lineage: "/data/NCBR/projects/NCBR-strongyloides/nematoda_odb10"
lineage_name: "nematoda_odb10"


